코틀린 예외처리
==============
코틀린의 예외처리는 자바와 비슷하다.     
함수를 호출하는 과정에서 오류가 발생하면 예외를 던질 수 있다.          
함수를 호출하는 쪽에서는 그 예외를 잡아서 처리할 수 있다.
   
발생한 예외를 함수 호출 단에서 처리하지 않으면    
함수 호출 스택을 거슬러 올라가면서 예외를 처리하는 부분이 나올 때까지 예외를 다시 던진다.           

```kt
if(percentage !in 0..100) {
    throw IllegalArgumentException("A percentage value must be between 0 and 100: $percentage")
}
```
예외도 다른 클래스와 마찬가지로 new 를 붙일 필요는 없다.      

```kt
val percentage = 
    if (number in 0..100)
        number
    else 
        throw IllegalArgumentException("A percentage value must be between 0 and 100: $number")
```
자바와 달리 `throw` 또한 `식`이기에 다른 식에 포함되어서 사용될 수 있다.     

# try, catch, finally    
자바와 마찬가지로 예외를 처리하려면 `try`와 `catch`, `finally` 절을 함께 사용한다.    

```kt
fun readNumber(reader: BufferedReader): Int? {
    try {
        val line = reader.readLine()
        return Integer.parseInt(line)
    }
    catch (e: NumberFormatException) {
        return null
    }
    finally {
        reader.close()
    }
}

fun main(args: Array<String>) {
    val reader = BufferedReader(StringReader("239"))
    println(readNumber(reader))
}

>>> 239
```
자바 코드와 가장 큰 차이는 메서드에 붙이는 `throws`가 없다는 점이다.         
  
코틀린에서는 함수가 던지는 예외를 지정하지 않고 발생한 예외를 잡아내도 되고 잡아내지 않아도 된다.           
자바에서의 `체크 예외`를 생각해보면 예외를 캐치해도 이를 해결하는 방법이 마땅히 없기에 실은 불필요하다.      
코틀린은 이런점을 고려해 `체크 예외`랑 `언체크 예외`를 구별하지 않는다.                    

더불어 코틀린은 `try-wtih-resource`을 지원하지 않지만 라이브러리 함수로 같은 기능을 구현한다.    

# try를 식으로 사용 








